# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

# Copy necessary files
WORKDIR /app
COPY db/items.db ./db/items.db
COPY python/ ./python/

# Install pip packages
WORKDIR /app/python
RUN pip install -r requirements.txt

CMD ["uvicorn", "main:app", "--reload", "--port", "9000", "--host=0.0.0.0"]